branch: master
dryRun: true
debug: true
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/npm'
    - npmPublish: false
  - - 'semantic-release-jira-releases'
    - projectId: 1
      releaseNameTemplate: 'Test v${version}'
      jiraHost: uphabit.atlassian.net
      released: true
      releaseDate: true
      ticketPrefixes:
        - TEST
        - FIX
        - UH
